language: node_js

node_js:
  - "10"

script:
  - npm run check
  - npm run build

after_script:
  - npm run coveralls

deploy:
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: main
  provider: pages
  skip_cleanup: true
  target_branch: artifacts
