name: Web App CI

on:
  push:
    branches:
      - main
    paths:
      - web-app/**
  pull_request:
    branches:
      - main
    paths:
      - web-app/**

jobs:
  build:

    defaults:
      run:
        working-directory: web-app

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          # last version
          - 14

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd web-app
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test
      - run: npm run build
